# Change these first
owner: jvinternetsolutions # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Webserver 1
    url: https://srv01.jvis.nl:2222
  - name: Backup server 1
    url: https://s3.eu-central-1.wasabisys.com
  - name: Status pagina
    url: https://status.jvis.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jvis.nl
  # baseUrl: /your-repo-name
  logoUrl: https://www.jvis.nl/wp-content/uploads/2019/11/logo.svg
  name: Uptime monitor
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
